version: "3.2"

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - type: bind
        source: c:/docker/data
        target: /export
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /export --console-address ":9001" 
