version: '3.2'

services:

  db:
    image: mdillon/postgis
    ports:
      - 5432:5432
    volumes:
      -  postgresql-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
      - 8001:8080

volumes:
    postgresql-volume: