version: "3.2"

services:
  db:
    image: kartoza/postgis:12.0
    ports:
      - 5432:5432
    volumes:
      - D:\docker\data\postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: natura_alert_v2
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      --auth: "md5"
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology

  adminer:
    image: adminer
    ports:
      - 8001:8080

