version: '3.9'

services:
   geoserver:
      image: kartoza/geoserver:2.20.4
      volumes:
        - C:\docker\data\geoserver:/opt/geoserver/data_dir
      ports:
        - 9090:8080
      environment:
        - GEOSERVER_ADMIN_PASSWORD=admin
        - GEOSERVER_ADMIN_USER=admin