version: '3'

services:
  martin:
    image: ghcr.io/maplibre/martin:latest
    ports:
      - "9100:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/scenario_db