version: "3.2"

services:
  minio:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - type: bind
        source: C:\docker\data\minio
        target: /export
    ports:
      - "9090:9000"
    command: server /export
