version: "3.2"

services:
  minio:
    image: 'bitnami/minio:latest'
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - type: bind
        source: C:\docker\minio
        target: /data
    ports:
      - "9000:9000"
      - "9001:9001"
