version: '3.1'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - C:\docker\data\mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: mysql
       MYSQL_DATABASE: mysql
       MYSQL_USER: mysql
       MYSQL_PASSWORD: mysql