version: '3.8'

services:
  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - /home/ollama:/root/.ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    ports: ["8002:8080"]
    depends_on:
      - ollama
    volumes:
      - ollama-webui:/app/backend/data
    environment:
      - 'OLLAMA_API_BASE_URL=http://host.docker.internal:11434/api'

volumes:
  ollama: {}
  ollama-webui: {}