version: "3"
  
services:
  redis-master:
    image: docker.io/bitnami/redis:7.2
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - C:\docker\data\redis:/bitnami

